entero numero, suma_serie
cadena [2] bandera
cadena [2] nombre
inicio
numero<-1
suma_serie<-0
bandera<-"T"
mientras numero<7 haga
suma_serie<-suma_serie+numero
escriba numero, " "
si bandera = "T" entonces
numero<- numero+1
bandera<- " H "
sino
numero<- numero+2
bandera<-"T"
fin si
fin mientras
escriba suma_serie
escriba bandera
escriba " Digite su numero: "
lea nombre
escriba "Su nombre es: ", nombre
fin